### ISSUE TITLE
ValueError: Unrecognised argument(s): encoding

### ISSUE THREAD

**Issue by Patatone** [FlavienRx/tgtg_notifier#4]
When I try to run it I get this error:

pi@raspberrypi:~/tgtg_notifier $ pipenv run python main.py
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    logging.basicConfig(encoding="utf-8", level=logging.INFO)
  File "/usr/lib/python3.7/logging/__init__.py", line 1921, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**Comment by Patatone** [comment]
Fixed, sorry:
https://github.com/xZaR3y4p/Img_link_to_local_markdown/issues/2
